---
title: "Super Netball Standard vs. Super Shot Simulations"
output: html_document
resource_files:
  - '.'
---

```{r setup, include=FALSE}
#Set the libPath to the conda environment
.libPaths("C:/Users/aafox/AppData/Local/Continuum/anaconda3/envs/super_netball_analysis_r/Lib/R/library")

knitr::opts_chunk$set(echo = FALSE)
```

---

#Test Heading

Test text...

```{r table, echo=FALSE}
#Load libraries
library(reactable)
library(htmltools)

##### TODO: remove SD column; have section specific colour coding, separate out the colour coding with a more diverging colour palette than three rgb codes, centre shot numbers, centre score outputs, sort out title team boldness...

#Load .csv file of super shot proportion simulations
simulationData <- read.csv("superSimSummary_afterRound4.csv", stringsAsFactors = FALSE)

#Set-up columns for table
nShots_cols <- c("meanShots", "lbShots", "ubShots")
mScore_cols <- c("meanScore_0_20", "meanScore_20_40", "meanScore_40_60", "meanScore_60_80", "meanScore_80_100")
# sdScore_cols <- c("sdScore_0_20", "sdScore_20_40", "sdScore_40_60", "sdScore_60_80", "sdScore_80_100")
# ubScore_cols <- c("ubScore_0_20", "ubScore_20_40", "ubScore_40_60", "ubScore_60_80", "ubScore_80_100")
# lbScore_cols <- c("lbScore_0_20", "lbScore_20_40", "lbScore_40_60", "lbScore_60_80", "lbScore_80_100")
# simulationData <- simulationData[, c("squadName", nShots_cols, mScore_cols, sdScore_cols, ubScore_cols, lbScore_cols)]
simulationData <- simulationData[, c("squadName", nShots_cols, mScore_cols)]

#Setup function for shots column
nShots_column <- function(maxWidth = 60, ...) {
  colDef(maxWidth = maxWidth, class = "cell number", ...)
}

#Identify max and min score for scaling score colours
maxCheckList = c("meanScore_0_20", "meanScore_20_40", "meanScore_40_60", "meanScore_60_80", "meanScore_80_100")
maxScoreVal = max(apply(simulationData[1,maxCheckList],2,max))
minCheckList = c("meanScore_0_20", "meanScore_20_40", "meanScore_40_60", "meanScore_60_80", "meanScore_80_100")
minScoreVal = min(apply(simulationData[,minCheckList],2,min))

# #Identify max and min score for scaling score colours
# maxCheckList = c("ubScore_0_20", "ubScore_20_40", "ubScore_40_60", "ubScore_60_80", "ubScore_80_100")
# maxScoreVal = max(apply(simulationData[,maxCheckList],2,max))
# minCheckList = c("lbScore_0_20", "lbScore_20_40", "lbScore_40_60", "lbScore_60_80", "lbScore_80_100")
# minScoreVal = min(apply(simulationData[,minCheckList],2,min))

#Identify max and min shots for scaling score colours
maxShotVal = max(simulationData$ubShots)
minShotVal = min(simulationData$lbShots)

# #Identify max and min score for deviation score colours
# sdCheckList = c("sdScore_0_20", "sdScore_20_40", "sdScore_40_60", "sdScore_60_80", "sdScore_80_100")
# maxSdVal = max(apply(simulationData[,sdCheckList],2,max))
# minSdVal = min(apply(simulationData[,sdCheckList],2,min))

#Setup functions for score columns
#### TODO: cell not being filled with colours...
scoreHigher_column <- function(maxWidth = 75, class = NULL, ...) {
  colDef(
    cell = function(value, index) {
      minVal <- min(simulationData$meanScore_0_20[index],
                        simulationData$meanScore_20_40[index],
                        simulationData$meanScore_40_60[index],
                        simulationData$meanScore_60_80[index],
                        simulationData$meanScore_80_100[index])
      maxVal <- max(simulationData$meanScore_0_20[index],
                        simulationData$meanScore_20_40[index],
                        simulationData$meanScore_40_60[index],
                        simulationData$meanScore_60_80[index],
                        simulationData$meanScore_80_100[index])
      scaled <- (value - minVal) / (maxVal - minVal)
      color <- higherBetter_color(scaled)
      value <- format(round(value, 1), nsmall = 1)
      div(style = list(color = "#111", background = color), value)
    },
    maxWidth = maxWidth,
    class = paste("cell number", class),
    ...
  )
}
sd_column <- function(maxWidth = 100, class = NULL, ...) {
  colDef(
    cell = formatScore,
    maxWidth = maxWidth,
    class = paste("cell number", class),
    style = function(value) {
      scaled = (value - minSdVal) / (maxSdVal - minSdVal)
      list(color = "#111", background = lowerBetter_color(scaled))
    },
    ...
  )
}

#Set formatter for score values
formatScore <- function(value) {
  formatC(paste0(round(value, 1)), width = 4)
}

#Set function to create scaled colour palette
make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}

#Set colour palette from green-red or red-green
higherBetter_color <- make_color_pal(rev(c("#00876c", "#4c9d85", "#79b2a0", "#a2c8bb", "#cbded7", "#f3f3f3", "#f3d1d1", "#f0afaf", "#e98c8e", "#e0676f", "#d43d51")), bias = 1.3)
lowerBetter_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 0.6)

#Create table
tbl <- reactable(
  simulationData,
  pagination = FALSE,
  defaultSorted = "meanShots",
  defaultSortOrder = "desc",
  defaultColGroup = colGroup(headerClass = "group-header"),
  columnGroups = list(
    colGroup(name = "Shot Number Summary", columns = nShots_cols),
    colGroup(name = "Mean Score with Different Super Shot Proportions", columns = mScore_cols)
    # colGroup(name = "SD of Score with Different Super Shot Proportions", columns = sdScore_cols),
    # colGroup(name = "Upper Bound of Score with Different Super Shot Proportions", columns = ubScore_cols),
    # colGroup(name = "Lower Bound of Score with Different Super Shot Proportions", columns = lbScore_cols)
  ),
  defaultColDef = colDef(class = "cell", headerClass = "header"),
  columns = list(
    squadName = colDef(
      defaultSortOrder = "asc",
      minWidth = 100,
      style = list(fontSize = "20px", fontWeight = "bold"),
      headerStyle = list(fontWeight = 700), 
      cell = function(value, index) {
        div(
          class = "squad",
          img(class = "logo", alt = paste(value, "logo"), src = sprintf("Images/%s.png", value)),
          div(class = "squad-name", value)
        )
      }
    ),
    
    #Set data for the number of shots columns
    meanShots = nShots_column(
      name = "Mean",
      defaultSortOrder = "asc",
      align = "center",
      cell = function(value) {
        scaled <- (value - min(simulationData$meanShots)) / (max(simulationData$meanShots) - min(simulationData$meanShots))
        color <- higherBetter_color(scaled)
        value <- format(round(value, 1), nsmall = 1)
        div(class = "nShot-val", style = list(background = color), value)
      }
    ),
    
    lbShots = nShots_column(
      name = "Min.",
      align = "center",
      cell = function(value) {
        scaled <- (value - min(simulationData$lbShots)) / (max(simulationData$lbShots) - min(simulationData$lbShots))
        color <- higherBetter_color(scaled)
        value <- format(round(value, 0), nsmall = 0)
        div(class = "nShot-val", style = list(background = color), value)
      }
    ),
    
    ubShots = nShots_column(
      name = "Max.",
      align = "center",
      cell = function(value) {
        scaled <- (value - min(simulationData$ubShots)) / (max(simulationData$ubShots) - min(simulationData$ubShots))
        color <- higherBetter_color(scaled)
        value <- format(round(value, 0), nsmall = 0)
        div(class = "nShot-val", style = list(background = color), value)
      }
    ),
    
    meanScore_0_20 = scoreHigher_column(name = "0%-20%", class = "border-left"),
    meanScore_20_40 = scoreHigher_column(name = "20%-40%"),
    meanScore_40_60 = scoreHigher_column(name = "40%-60%"),
    meanScore_60_80 = scoreHigher_column(name = "60%-80%"),
    meanScore_80_100 = scoreHigher_column(name = "80%-100%")

    # sdScore_0_20 = sd_column(name = "0%-20%", class = "border-left"),
    # sdScore_20_40 = sd_column(name = "20%-40%"),
    # sdScore_40_60 = sd_column(name = "40%-60%"),
    # sdScore_60_80 = sd_column(name = "60%-80%"),
    # sdScore_80_100 = sd_column(name = "80%-100%"),
    # 
    # ubScore_0_20 = scoreHigher_column(name = "0%-20%", class = "border-left"),
    # ubScore_20_40 = scoreHigher_column(name = "20%-40%"),
    # ubScore_40_60 = scoreHigher_column(name = "40%-60%"),
    # ubScore_60_80 = scoreHigher_column(name = "60%-80%"),
    # ubScore_80_100 = scoreHigher_column(name = "80%-100%"),
    # 
    # lbScore_0_20 = scoreHigher_column(name = "0%-20%", class = "border-left"),
    # lbScore_20_40 = scoreHigher_column(name = "20%-40%"),
    # lbScore_40_60 = scoreHigher_column(name = "40%-60%"),
    # lbScore_60_80 = scoreHigher_column(name = "60%-80%"),
    # lbScore_80_100 = scoreHigher_column(name = "80%-100%")
    
  ),
  # Emphasize borders between groups when sorting by group
  rowClass = JS("
    function(rowInfo, state) {
      const firstSorted = state.sorted[0]
      if (firstSorted && firstSorted.id === 'group') {
        const nextRow = state.pageRows[rowInfo.viewIndex + 1]
        if (nextRow && rowInfo.row.group !== nextRow.group) {
          return 'group-last'
        }
      }
    }"
  ),
  showSortIcon = FALSE,
  borderless = TRUE,
  class = "score-table"
)

div(class = "scores",
  div(class = "title",
    h2("Score Predictions with Different Super Shot Proportions"),
    "Mean, standard deviation (SD), and upper & lower bounds for scores from 5 minute quarter simulations across different Super Netball teams."
  ),
  tbl,
  "Simulations based on shooting data from Super Shot periods across 4 rounds of SSN 2020."
)
```

---

Sample text...

```{r ref.label="table", eval=FALSE}
```

```{r}
tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```

```{css}
.scores {
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
}

.title {
  margin: 18px 0;
  font-size: 16px;
}

.title h2 {
  font-size: 20px;
  font-weight: 600;
}

.score-table {
  margin-bottom: 20px;
}

/* Align header text to the bottom */
.header,
.group-header {
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}

.header {
  border-bottom-color: #555;
  font-size: 13px;
  font-weight: 400;
  text-transform: uppercase;
}

/* Highlight headers when sorting */
.header:hover,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #eee;
}

.border-left {
  border-left: 2px solid #555;
}

/* Use box-shadow to create row borders that appear behind vertical borders */
.cell {
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
}

.group-last .cell {
  box-shadow: inset 0 -2px 0 #555;
}

.squad {
  display: flex;
  align-items: baseline;
}

.record {
  margin-left: 5px;
  color: #999;
  font-size: 13px;
}

squad-name {
  font-size: 24px;
  font-weight: 700;
}

.logo {
  margin-right: 8px;
  margin-top: 1px;
  margin-bottom: 1px;
  height: 30px;
}

.group {
  font-size: 19px;
}

.number {
  # font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 16px;
  line-height: 30px;
  # white-space: pre;
}

.nShot-val {
  width: 40px;
  height: 40px;
  border: 1px solid rgba(0, 0, 0, 0.03);
  border-radius: 50%;
  color: #000;
  font-size: 14px;
  align: "center";
  letter-spacing: 0px;
}

.score-val {
  # margin-right: 0px;
  # margin-left: 0px;
  # margin-top: 0px;
  # margin-bottom: 0px;
}

```


```{css echo=FALSE}
/* rmarkdown html documents */
.main-container {
  max-width: 1054px !important;
}

h1.title {
  display: none;
}

/* pkgdown articles */
.contents {
  width: 1054px;
}

.page-header {
  display: none;
}
```
